export var skillList={
    ['658']:{
        'Struggle':false,
        'Mimic':false,
        'Belly Drum':false,
        'Flare Blitz':false,
        'Dragon Claw':false,
        'Swords Dance':false,
        'Golden Shuriken':false,
        'Water Shuriken':false,
        'Hydro Pump':false,
        'Double Team':false,
        'Night Slash':false,
        'Haze':false,
        'Role Play':false,
        'Mat Block':false,
        'Pound':false,
        'Growl':false,
        'Bubble':false,
        'Quick Attack':false,
        'Lick':false,
        'Water Pulse':false,
        'Smokescreen':false,
        'Shadow Sneak':false,
        // 'Spikes':false,
        // 'Feint Attack':false,
        'Extrasensory':false,
        // 'Substitute':false,
    },
}

export var viewList={
    'Water Shuriken':false,
    'Hydro Pump':false,
    'Double Team':false,
    'Night Slash':false,
    'Haze':false,
    'Mat Block':false,
    'Pound':false,
    'Growl':false,
    'Bubble':false,
    'Quick Attack':false,
    'Lick':false,
    'Water Pulse':false,
    'Smokescreen':false,
    'Shadow Sneak':false,
    // 'Spikes':false,
    // 'Feint Attack':false,
    'Extrasensory':false,
    // 'Substitute':false,
}

export var randomSkill={
    1:'Water Shuriken',
    2:'Hydro Pump',
    3:'Double Team',
    4:'Night Slash',
    5:'Haze',
    6:'Mat Block',
    7:'Pound',
    8:'Growl',
    9:'Bubble',
    10:'Quick Attack',
    11:'Lick',
    12:'Water Pulse',
    13:'Smokescreen',
    14:'Shadow Sneak',
    15:'Extrasensory',
    16:'Water Shuriken',
}